//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace WebApplicationTest.Model
{
    using System;
    using System.Collections.Generic;
    
    public partial class DetailTransaction
    {
        public int detailid { get; set; }
        public Nullable<int> transaction_id { get; set; }
        public Nullable<int> hotel_id { get; set; }
        public Nullable<decimal> price { get; set; }
        public Nullable<int> quantity { get; set; }
        public Nullable<System.DateTime> startDate { get; set; }
        public Nullable<System.DateTime> endDate { get; set; }
        public string roomType { get; set; }
    
        public virtual Hotel Hotel { get; set; }
        public virtual HeaderTransaction HeaderTransaction { get; set; }
    }
}
